version: 4.1.0.{build}
branches:
  except:
  - gh-pages
skip_tags: true
os: Visual Studio 2015
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: Dg2RuAuaLz+RP1kNxH6LqoEbVhsRIYI15lObO46PoTFYFwP87lXojzI91vdk+Km5
  skip_symbols: false
  artifact: 
  on:
    branch: master
- provider: GitHub
  auth_token:
    secure: QUNpmgp2dvA0M/Veuo7NJkjNXBJOxFsDAartHAjZfKhaLzFKdITHHhmST6ZUTdxu
  on:
    branch: master
